name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  release-repo:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
        with:
          repository: jayanth9652/release   
          token: ${{ secrets.MY_PAT }}
          ref: master 
      - name: creating release.json artifact for tagging master branch
        uses: actions/upload-artifact@v2
        with:
          name: Anudan-Release
          path: release.json
          retention-days: 5     

  anudan-app:
    runs-on: ubuntu-latest
    needs: release-repo
    if: github.ref == 'refs/heads/main' 
    steps:
     - name: check out gms-service master
       uses: actions/checkout@master
       with:
          repository: jayanth9652/gms-service  
          token: ${{ secrets.MY_PAT }}          
          ref: master 
     - name: Anudan Release artifact downloading      
       uses: actions/download-artifact@v2
       with:
          name: Anudan-Release     

     - name: list files
       run: |  
            #!/bin/bash
            DATE=
            git log --pretty=format:"%ad || %h || %s || Author:%an " --date=short | sort -r | while read line
            do
            temp=`echo $line | egrep -v '(Resolve Conflict From)'`
            if [ "$temp" = "" ]
            then
                continue
            else
                NEWDATE=`echo $temp |  awk  '{print $1}'`
                if [ "$NEWDATE" = "$DATE" ]
                then
                    echo $temp | awk '{$1="";$2="";print}' >> releaseNotes.txt
                else
                    echo >> releaseNotes.txt
                    DATE=$NEWDATE
                    echo `date --date=$DATE +%d-%B-%Y` >> releaseNotes.txt
                    echo $temp | awk '{$1="";$2="";print}' >> releaseNotes.txt
                fi
            fi
            done 
            ls -lrt
            pwd 
     - name: list file final
       run: | 
       pwd
       ls -lrt

        cat /home/runner/work/demo-frontend/demo-frontend/releaseNotes


