name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  release-repo:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
        with:
          repository: jayanth9652/release   
          token: ${{ secrets.MY_PAT }}
          ref: master 
      - name: creating release.json artifact for tagging master branch
        uses: actions/upload-artifact@v2
        with:
          name: Anudan-Release
          path: release.json
          retention-days: 5     


  Notify-on-email:
    runs-on: ubuntu-latest
    if: always()
    needs: [release-repo]
    name: EmailNotify
    steps:
      - name: Send some mail
        uses: wadeww/send-email-action@master
        with:
          server_address: smtp.gmail.com
          port: ${{ secrets.SMTP_SERVER_PORT }}
          username: ${{ secrets.AUTH_USER }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Workflow finished
          body: ${{github.repository}} 1)Buildjob- ${{needs.release-repo.result}} 2)Test- ${{needs.anudan-app.result}} 
          to:  test-874d3104@appmaildev.com
          from: donotreply@anudan.org
           



