name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  DEV-Frontend-Build:

    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' 
    strategy:
      matrix:
       node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
      with:
        repository: jayanth9652/anudan-app 
        token: ${{ secrets.MY_PAT }}
        ref: dev
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
       node-version: ${{ matrix.node-version }}
       cache: 'npm'
    - run: pwd
    #- run: ls -lrt 
    #- run: node --version
    #- run: npm --version 
    #- run: java -version 
    #- run: npm install -g @angular/cli@latest
    #- run: ng version
    - run: npm install --save-dev @angular-devkit/build-angular
    #- run: npm ci
    #- run: ng build --prod --no-aot --build-optimizer false
    #- run: npm run build --if-present
    #- run: ng build --aot --output-hashing=all --configuration=production
    #- run: ng build --aot --output-hashing=all --configuration=production --build-optimizer false
    - run: npm install
    - run: ng build --aot --output-hashing=all --prod
    #- run: ng build --aot --output-hashing=all --configuration=production
    #- run: ng build --stats-json
    #- run: ng build --stats-json --source-map=false
    #- run: ng build --source-map=false
    #- run: ng --build optimizer=false 
    - run: ls -lrt dist   

    - name: anudan frontend artifact uploading
      uses: actions/upload-artifact@v2
      with:
          name: dist
          path: dist/**
          retention-days: 5
